name: Something Good
favicon: null
layout_spectrum: 0.24287
typography_spectrum: 0.73734
title: Something Good Creative House
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#8bc2f0'
    - '#080d11'
    - '#a89773'
    - '#5e7689'
  brandStrength: 0.6118340995162725
  lightness: 0.22267665062099695
  saturation: 0.04708438692614436
  rhythmicContrast: 0.23368705972097814
purpose: []
