name: somethinggood
favicon: null
layout_spectrum: 0.3109341515228152
typography_spectrum: 0.7985862742643803
title: Something Good Creative House
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6118340995162725
  lightness: 0.22267665062099695
  saturation: 0.04708438692614436
  rhythmicContrast: 0.23368705972097814
purpose: []
